### ISSUE TITLE
How to make the element "disappear"?

### ISSUE THREAD

**Issue by eskaigualker** [emn178/jquery-animations-tile#1]
For example, we apply a "flyOut" effect. After it finished, the element comes back again. Is there a way to avoid this?

Thank you

**Comment by emn178** [comment]
Hi,

You can set [fillMode](https://github.com/emn178/jquery-animations#fillmode-string-default-animation-define-or-none) to `forwards`.
You also can see the Flake and Blow effect in this [demo](http://emn178.github.io/jquery-animations-tile/samples/tile/).

And if you want to remove element after animation, you can use callback option [end](https://github.com/emn178/jquery-animations#end-functionoptions) and [reset()](https://github.com/emn178/jquery-animations#reset) before remove() to do that.

Best regards.

**Comment by eskaigualker** [comment]
That's it, thank you very much!
